version: 2.1
jobs:
  build:
    working_directory: ~/telescope
    docker:
      - image: circleci/node:lts
      - image: circleci/redis:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Create default env variables
          command: cp env.example .env
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Execute tests
          command: npm run test-ci
      - run:
          name: Build Telescope
          command: |
            docker build -t $DOCKER_USER/telescope .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $DOCKER_USER/telescope
  deploy:
    working_directory: ~/telescope
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Install AWS CLI
          command: sudo pip install awsebcli
      - run:
          name: Create AWS credential
          command: |
            set -x
            set -env
            mkdir ~/.aws
            touch ~/.aws/config
            chmod ~/.aws/config
            echo "[profile prod]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run:
          name: Deploy to EB
          command: |
            eb use TelescopeGatsby-env
            eb deploy

workflows:
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - deployment
